/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ITEVAD"
 * 	found in "itevad.asn1"
 */

#ifndef	_AskContent_H_
#define	_AskContent_H_


#include <asn_application.h>

/* Including external dependencies */
#include <IA5String.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AskContent */
typedef IA5String_t	 AskContent_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AskContent;
asn_struct_free_f AskContent_free;
asn_struct_print_f AskContent_print;
asn_constr_check_f AskContent_constraint;
ber_type_decoder_f AskContent_decode_ber;
der_type_encoder_f AskContent_encode_der;
xer_type_decoder_f AskContent_decode_xer;
xer_type_encoder_f AskContent_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _AskContent_H_ */
