/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ITEVAD"
 * 	found in "itevad.asn1"
 */

#include <asn_internal.h>

#include "MessageBody.h"

static asn_TYPE_member_t asn_MBR_MessageBody_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MessageBody, choice.messageRequest),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MessageRequest,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"messageRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MessageBody, choice.messageReply),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MessageReply,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"messageReply"
		},
};
static asn_TYPE_tag2member_t asn_MAP_MessageBody_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* messageRequest at 30 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* messageReply at 32 */
};
static asn_CHOICE_specifics_t asn_SPC_MessageBody_specs_1 = {
	sizeof(struct MessageBody),
	offsetof(struct MessageBody, _asn_ctx),
	offsetof(struct MessageBody, present),
	sizeof(((struct MessageBody *)0)->present),
	asn_MAP_MessageBody_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_MessageBody = {
	"MessageBody",
	"MessageBody",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_MessageBody_1,
	2,	/* Elements count */
	&asn_SPC_MessageBody_specs_1	/* Additional specs */
};

