/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ITEVAD"
 * 	found in "itevad.asn1"
 */

#ifndef	_MessageReply_H_
#define	_MessageReply_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TransactionId.h"
#include "AnswerContent.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MessageReply */
typedef struct MessageReply {
	TransactionId_t	 transactionId;
	AnswerContent_t	 answerContent;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MessageReply_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MessageReply;

#ifdef __cplusplus
}
#endif

#endif	/* _MessageReply_H_ */
